-- ==========================================
-- SCHEMA PARA POLLA MUNDIALISTA 2026 (SUPABASE / POSTGRESQL)
-- ==========================================

-- Habilitar extensión para UUIDs si no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    foto_url TEXT,
    puntos_totales INTEGER DEFAULT 0,
    rol VARCHAR(20) DEFAULT 'user' CHECK (rol IN ('user', 'admin')),
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) para seguridad en Supabase
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para Usuarios
CREATE POLICY "Permitir lectura de usuarios a todos" ON public.usuarios FOR SELECT USING (true);
CREATE POLICY "Permitir inserción de usuarios a todos" ON public.usuarios FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualización de datos a sí mismo o Admin" ON public.usuarios 
    FOR UPDATE USING (auth.uid() = id OR EXISTS (SELECT 1 FROM public.usuarios WHERE id = auth.uid() AND rol = 'admin'));

-- 2. TABLA DE PARTIDOS
CREATE TABLE IF NOT EXISTS public.partidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_local VARCHAR(100) NOT NULL,
    equipo_visitante VARCHAR(100) NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL,
    goles_local_real INTEGER,
    goles_visitante_real INTEGER,
    estado VARCHAR(20) DEFAULT 'programado' CHECK (estado IN ('programado', 'jugado')),
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.partidos ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para Partidos
CREATE POLICY "Permitir lectura de partidos a todos" ON public.partidos FOR SELECT USING (true);
CREATE POLICY "Permitir modificación de partidos solo a Admins" ON public.partidos 
    FOR ALL USING (EXISTS (SELECT 1 FROM public.usuarios WHERE id = auth.uid() AND rol = 'admin'));

-- 3. TABLA DE APUESTAS
CREATE TABLE IF NOT EXISTS public.apuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    partid_id BIGINT REFERENCES public.partidos(id) ON DELETE CASCADE,
    prediccion_ganador VARCHAR(2) CHECK (prediccion_ganador IN ('L', 'E', 'V', 'AA', NULL)), -- L: Local, E: Empate, V: Visitante, AA: Ambos Anotan
    goles_local_pred INTEGER CHECK (goles_local_pred >= 0),
    goles_visitante_pred INTEGER CHECK (goles_visitante_pred >= 0),
    puntos_ganados INTEGER DEFAULT 0,
    fecha_apuesta TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unica_apuesta_por_usuario_partido UNIQUE (usuario_id, partid_id)
);

ALTER TABLE public.apuestas ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad para Apuestas
CREATE POLICY "Permitir lectura de apuestas a todos" ON public.apuestas FOR SELECT USING (true);
CREATE POLICY "Permitir apuestas de usuarios autenticados" ON public.apuestas FOR INSERT WITH CHECK (auth.uid() = usuario_id);
CREATE POLICY "Permitir actualización de apuesta propia antes del bloqueo" ON public.apuestas 
    FOR UPDATE USING (
        auth.uid() = usuario_id 
        AND EXISTS (
            SELECT 1 FROM public.partidos 
            WHERE id = partid_id 
            AND fecha_hora > (NOW() + INTERVAL '10 minutes')
        )
    );

-- ==========================================
-- FUNCIONES Y TRIGGERS PARA EL CÁLCULO DE PUNTOS
-- ==========================================

-- Función para calcular puntos de una apuesta individual
CREATE OR REPLACE FUNCTION public.calcular_puntos(
    goles_local_real INT, goles_visitante_real INT,
    goles_local_pred INT, goles_visitante_pred INT,
    prediccion_ganador VARCHAR(2)
) RETURNS INTEGER AS $$
DECLARE
    resultado_real CHAR(1);
    resultado_pred CHAR(1);
BEGIN
    -- Si no hay resultado real cargado, la apuesta no suma puntos todavía
    IF goles_local_real IS NULL OR goles_visitante_real IS NULL THEN
        RETURN 0;
    END IF;

    -- Obtener resultado real
    IF goles_local_real > goles_visitante_real THEN
        resultado_real := 'L';
    ELSIF goles_local_real < goles_visitante_real THEN
        resultado_real := 'V';
    ELSE
        resultado_real := 'E';
    END IF;

    -- Caso 1: Se apostó con Marcador Exacto (goles_local_pred y goles_visitante_pred no son nulos)
    IF goles_local_pred IS NOT NULL AND goles_visitante_pred IS NOT NULL THEN
        -- Si acertó marcador exacto: 3 puntos
        IF goles_local_real = goles_local_pred AND goles_visitante_real = goles_visitante_pred THEN
            RETURN 3;
        END IF;

        -- Obtener resultado predicho por goles
        IF goles_local_pred > goles_visitante_pred THEN
            resultado_pred := 'L';
        ELSIF goles_local_pred < goles_visitante_pred THEN
            resultado_pred := 'V';
        ELSE
            resultado_pred := 'E';
        END IF;

        -- Si acertó solo al ganador/empate (pero no marcador exacto): 1 punto
        IF resultado_real = resultado_pred THEN
            RETURN 1;
        END IF;

    -- Caso 2: Solo se apostó al Ganador/Empate directamente (sin goles específicos)
    ELSIF prediccion_ganador IS NOT NULL THEN
        -- Si es Empate ('E') o ganador tradicional ('L', 'V')
        IF prediccion_ganador = 'E' AND resultado_real = 'E' THEN
            RETURN 1;
        ELSIF prediccion_ganador = 'L' AND resultado_real = 'L' THEN
            RETURN 1;
        ELSIF prediccion_ganador = 'V' AND resultado_real = 'V' THEN
            RETURN 1;
        -- Si es Ambos Anotan ('AA') y ambos marcaron gol
        ELSIF prediccion_ganador = 'AA' AND goles_local_real > 0 AND goles_visitante_real > 0 THEN
            RETURN 1;
        END IF;
    END IF;

    -- No acertó nada
    RETURN 0;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Trigger para recalcular puntos de las apuestas cuando se actualiza el marcador de un partido
CREATE OR REPLACE FUNCTION public.trg_actualizar_puntos_apuestas()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo procesar si el estado cambia a 'jugado' o se cambian los goles reales
    IF (NEW.estado = 'jugado' AND (OLD.estado != 'jugado' OR OLD.goles_local_real IS DISTINCT FROM NEW.goles_local_real OR OLD.goles_visitante_real IS DISTINCT FROM NEW.goles_visitante_real)) THEN
        -- 1. Actualizar puntos en cada apuesta de este partido
        UPDATE public.apuestas
        SET puntos_ganados = public.calcular_puntos(
            NEW.goles_local_real, NEW.goles_visitante_real,
            goles_local_pred, goles_visitante_pred,
            prediccion_ganador
        )
        WHERE partid_id = NEW.id;

        -- 2. Recalcular puntos totales de todos los usuarios
        UPDATE public.usuarios u
        SET puntos_totales = COALESCE(
            (SELECT SUM(puntos_ganados) FROM public.apuestas a WHERE a.usuario_id = u.id),
            0
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear el trigger sobre la tabla partidos
DROP TRIGGER IF EXISTS trg_partidos_actualizar_puntos ON public.partidos;
CREATE TRIGGER trg_partidos_actualizar_puntos
AFTER UPDATE OF goles_local_real, goles_visitante_real, estado ON public.partidos
FOR EACH ROW
EXECUTE FUNCTION public.trg_actualizar_puntos_apuestas();
